plugins {
    id "com.android.application"
}

android {
    namespace "com.newhim3.studyhub"
    compileSdk 35

    defaultConfig {
        applicationId "com.newhim3.studyhub"
        minSdk 23
        targetSdk 35
        def buildNumber = project.findProperty("versionCode") ?: "1"
        versionCode buildNumber.toInteger()
        versionName "1.0." + buildNumber
    }

    signingConfigs {
        release {
            storeFile file(project.findProperty("storeFile") ?: "release.keystore")
            storePassword project.findProperty("storePassword") ?: ""
            keyAlias project.findProperty("keyAlias") ?: "mayuan"
            keyPassword project.findProperty("keyPassword") ?: ""
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}
