plugins {
    id "com.android.application"
}

android {
    namespace "com.newhim3.studyhub"
    compileSdk 35

    defaultConfig {
        applicationId "com.newhim3.studyhub"
        minSdk 23
        targetSdk 35
        def buildNumber = project.findProperty("versionCode") ?: "1"
        versionCode buildNumber.toInteger()
        versionName "1.0." + buildNumber
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}
